# -*- coding: utf-8 -*-
"""board.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UT1h55xVAaYh49gbnzfaiSSOoF7kqzVi
"""

def PrintBoard():
  gb1 = ['-', '-', '-']
  gb2 = ['-', '-', '-']
  gb3 = ['-', '-', '-']

  game_board = []
  game_board.append(gb1)
  game_board.append(gb2)
  game_board.append(gb3)

  
  for i in game_board:
    print(i)

PrintBoard()